# Coral configuration file

# Environment: dev, staging, prod
env: 'dev'

# Email configuration
email:
  # Default sender address
  sender: 'no-reply@the-hub.ai'
  # Test email (if set, all emails go here)
  test: 'daniel.guo@vivalabs.com.au'

# AWS configuration
aws:
  # AWS region
  region: 'ap-southeast-2'

# Worker pool configuration
worker:
  # Number of worker goroutines
  pool_size: 5
  # Delay between email sends in milliseconds
  delay_ms: 1000

# Transfer configuration
transfer:
  # Default values for command line arguments
  type: 'PIF'
  input: 'data/pif_club_transfer.csv'
